### ISSUE TITLE
Code for using the RF function of the MCU as serial port [question]

### ISSUE THREAD

**Issue by mrWheel** [bitbank2/SmartResponseXE#10]
Hi Larry,

Thanks for this great library! 

Although no updates for a long time I wonder if there is some code to use the RF functionality of the MCU.

It would be fantastic if we could use this RF hardware as a serial port to communicate between the Smart Responder (as a terminal) and, for instance, a stand-alone RF transiever  to communicate with an external device.

Do you have any plans for this?

**Comment by bitbank2** [comment]
Hi MrWheel,
Unfortunately I no longer own any of these devices. Some others have posted code for using the RF part.
