### ISSUE TITLE
Issues installing the bootloader

### ISSUE THREAD

**Issue by ea3iav** [bitbank2/SmartResponseXE#12]
First: I am using the ISP procedure, but, it is not clear if Smart response needs 3 or 5V on the ASPUSB. Also, does the SRXE needs to be powered up? While trying to flash the bootloader?
Is there any other way to send this hex? Maybe some tool called extreme burner tool. Sorry too much questions. 
Thank you

**Comment by bitbank2** [comment]
I no longer own this type of device nor remember the details you're asking about. I'm sorry.
