### ISSUE TITLE
Line pattern for one of the gray levels

### ISSUE THREAD

**Issue by fdufnews** [bitbank2/SmartResponseXE#5]
Thank you for that library. It was a great help for me when starting to play with the SMART Response XE terminal.
I have found a little error in your code.
When you fill a rectangle, for example, there is a visible line pattern for one of the gray levels.
Currently, bColorToByte is defined as is:
`static byte bColorToByte[4] = {0, 0x4A, 0x92, 0xff};`

Applying the datasheet
 pix0 | pix1 | pix2 | bColorByte
 1 1 1| 1 1 1| 1 1  |  0xFF
 1 0 0| 1 0 0| 1 0  |  0x92
 0 1 0| 0 1 0| 0 1  |  **0x49**
 0 0 0| 0 0 0| 0 0  |  0x00

To correct it, bColorToByte shall be defined as is:
`static byte bColorToByte[4] = {0, 0x49, 0x92, 0xff};`

**Comment by bitbank2** [comment]
Would you mind doing a pull request? I don't have an easy way to test this anymore.
Thanks.
