### ISSUE TITLE
different fonts

### ISSUE THREAD

**Issue by kd8bxp** [bitbank2/SmartResponseXE#7]
Here is what I've been working on for the past couple of days - it contains 16 or 17 different fonts that can be changed as needed.
To be honest I didn't make these fonts I modified them slightly to work with the library, I modified the library slightly to work with the changing the fonts.
The fonts were found  https://jared.geek.nz/2014/jan/custom-fonts-for-microcontrollers as noted in the sketch there is a fontgen.py script that is included I've not been able to get it to work correctly.
I would create a pull request, but some of the fonts don't work quite as well as others do. And some of the spacing is off a bit. (variable spaced fonts seem to have this issue) monospaced fonts seem to work pretty well.
Anyway I thought I'd share what I was doing. As I'm still learning I'm sure there is possible a better way to do some of this.
Although even with 4 fonts loaded in, the sketch is only using 5% of program storage space, so that seems pretty good to me.
The fonts used are included in the data directory, the fonts directory contains the header files. I think the sketch is pretty self explanatory.
Thanks again for the help with this, and the library.  Hoping I've offered something that may help improve on the work in the future.
[Font_test2.zip](https://github.com/bitbank2/SmartResponseXE/files/6247220/Font_test2.zip)

**Comment by bitbank2** [comment]
Unfortunately I no longer own any SmartResponseXE units. I had to abandon them after my last move. I would suggest creating a fork of my repo and continuing your work there. I can't test it, so I won't be making any new changes.
