### ISSUE TITLE
The fifth column of the keyboard

### ISSUE THREAD

**Issue by gc986** [bitbank2/SmartResponseXE#8]
Hello! Thank you for project :+1: 
I wrote a simple keyboard testing application. For some reason, when I click on the buttons of the fifth column (5, T, G, V), the system is defined as if I click on the corresponding buttons of the last column (0, P ...). What am I doing wrong? 

`#include <SmartResponseXE.h>
#include <string.h>

void setup() {
  SRXEInit(0xe7, 0xd6, 0xa2);
  
  Serial.begin(9600);
}

void loop() {

  String str = "char:  ";

  byte key_ = SRXEGetKey();
    
  char charVar = char (key_);
  str += charVar;
    
  int strLen = str.length() + 1;
  char charArray[strLen];
  str.toCharArray(charArray, strLen);
    
  SRXEWriteString(0, 0, charArray, FONT_LARGE, 3, 0);

  delay(100);
}`

**Comment by bitbank2** [comment]
I no longer own any of these devices, but I remember that using one of the serial ports interfered with the keyboard since they share a GPIO pin. I'm sorry, but I don't have any more info than that.

**Comment by gc986** [comment]
Thanks for the answer! I'll try to think of something :)
