### ISSUE TITLE
power usage greater than original production code?

### ISSUE THREAD

**Issue by bradanlane** [bitbank2/SmartResponseXE#9]
I've been working with several different "libraries" for the SMART Response XE _(most of which are closely based on this repository)_.

When I test the power consumption of the original code on a production device, the steady state is about 1.5mA (with content visible on the LCD) and the sleep state is about 200uA.

All of the repositories I have tested have a steady state is about 7-9mA and the sleep state is 500-600uA.

Have you found any documentation which may help identify code which could reduce the power usage. It's not clear to me if the issue is the LCD or a pin controlling some other hardware on the PCB.

**Comment by bitbank2** [comment]
With AVR, it's all about disabling the ADC and sleeping properly. There is an abundance of documentation on this very topic.

**Comment by bradanlane** [comment]
I am aware of ADC and proper pin configuration for sleep mode of AVR chips. My own projects sleep at 200nA.

given the SMART Response XE has significant hardware attached to the chip, and the significant delta between the power usage of the commercial firmware vs this library, I am performing painstaking experiments to identify the issue.

I hope this issue (open or closed) may prompt others to collaborate. I am not yet making much progress.
